#!/usr/bin/env python3
"""Write out every line Nura says in the Collection, so her voice can be recorded for all
of them at once (the three lines we have came from ElevenLabs; the rest use the browser's
own voice until they exist).

Usage: python3 tools/nura_script.py            -> ref/nura-script.json
Then, with the ElevenLabs key and Nura's voice id in the environment:
  ELEVEN_API_KEY=... ELEVEN_VOICE_ID=... python3 tools/nura_script.py --record
writes media/audio/nura-<key>.mp3 for every line that has no recording yet, and build.py
picks them up by key (items by slug, fixed lines by name).
"""
import json, os, re, sys, time, urllib.request

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
html = open(os.path.join(HERE, "docs", "explore", "index.html"), encoding="utf-8").read()
cfg = json.loads(re.search(r"WALK_CFG=(\{.*?\})</script>", html, re.S).group(1))

lines = {}
FIXED = {
    "greeting": "I am Nura. Drag anything to turn it, save the ones you like, and see how many of the six badges you can find.",
    "welcome-back": "Welcome back. Let us see what you have not looked at yet.",
    "offer-demo": "Want to see how one of these is scanned? I can show you, right here.",
    "badge-first-turn": "You turned it. Now you are really looking.",
    "badge-curator": "Five saved. You have a collection of your own now.",
    "badge-listener": "You keep asking for more. I like that.",
    "badge-surveyor": "You have seen something from every place we scanned.",
    "badge-guardian": "You shared one. That is how these stay remembered.",
    "badge-completionist": "Every single object. Thank you for looking at all of them.",
    "room-intro": "Everything they made, in one room. Pick one to bring it closer.",
    "made-intro": "No scan here. A volunteer built this from nothing.",
}
for k, v in FIXED.items():
    lines[k] = {"text": v, "kind": "fixed"}
for it in cfg["items"]:
    if it.get("hi"):
        lines[it["slug"]] = {"text": it["hi"], "kind": "opener", "title": it["title"]}
    if it.get("note"):
        lines[it["slug"] + "--more"] = {"text": it["note"], "kind": "more", "title": it["title"]}
have = {f[len("nura-"):-4] for f in os.listdir(os.path.join(HERE, "media", "audio")) if f.endswith(".mp3")}
for k in lines:
    lines[k]["recorded"] = k in have
total = sum(len(v["text"]) for v in lines.values())
out = os.path.join(HERE, "ref", "nura-script.json")
json.dump({"_what": "Every line Nura says in the Collection, keyed by object slug (openers), slug--more (the longer line) or a fixed name. Generated by tools/nura_script.py from the built page.",
           "characters_total": total, "lines": lines}, open(out, "w"), indent=1, ensure_ascii=False)
print(f"{len(lines)} lines, {total:,} characters -> ref/nura-script.json")

if "--record" in sys.argv:
    key = os.environ.get("ELEVEN_API_KEY", "").strip(); voice = os.environ.get("ELEVEN_VOICE_ID", "").strip()
    if not key or not voice:
        sys.exit("set ELEVEN_API_KEY and ELEVEN_VOICE_ID in the environment first")
    for k, v in lines.items():
        if v["recorded"]:
            continue
        body = json.dumps({"text": v["text"], "model_id": "eleven_multilingual_v2",
                           "voice_settings": {"stability": 0.45, "similarity_boost": 0.8, "style": 0.35}}).encode()
        req = urllib.request.Request(f"https://api.elevenlabs.io/v1/text-to-speech/{voice}?output_format=mp3_44100_96",
                                     data=body, headers={"xi-api-key": key, "Content-Type": "application/json"})
        try:
            with urllib.request.urlopen(req, timeout=120) as r:
                open(os.path.join(HERE, "media", "audio", f"nura-{k}.mp3"), "wb").write(r.read())
            print("recorded", k)
        except urllib.error.HTTPError as e:
            print("failed", k, e.code, e.read()[:200]); break
        time.sleep(0.4)
